// TODO: Build data set arrays and functions to generate random data

// seed arrays

const names = [
    "Tom",
    "Dave",
    "Patrick",
    "Fleece",
    "Kim",
    "James",
    "Emma",
    "Oliver",
    "Ava",
    "William",
    "Sophia",
    "Benjamin",
    "Isabella",
    "Mia",
    "Ethan",
    "Charlotte",
    "Noah",
    "Amelia",
    "Lucas",
    "Harper",
    "Liam",
    "Evelyn",
    "Mason",
    "Abigail",
    "Logan",
    "Emily",
    "Jackson",
    "Ella",
    "Alexander",
    "Madison",
    "Sebastian",
    "Scarlett",
    "Michael",
    "Victoria",
    "Elijah",
    "Grace",
    "Daniel",
    "Chloe",
    "Matthew",
    "Lily",
    "Aiden",
    "Aria",
    "Henry",
    "Penelope",
    "Joseph",
    "Avery",
    "Samuel",
    "Mila",
    "David",
    "Aurora",
    "Owen",
    "Hazel",
    "Wyatt",
    "Sofia",
    "John",
    "Nora",
    "Jonathan",
    "Ellie",
    "Caleb",
    "Aubrey",
    "Isaac",
    "Addison",
    "Luke",
    "Stella",
    "Ezra",
    "Bella",
];

const thoughts =  [
    "The road not taken leads to new discoveries.",
    "In the middle of difficulty lies opportunity.",
    "Hope is the thing with feathers that perches in the soul.",
    "Do not go gentle into that good night.",
    "Beauty is truth, truth beauty.",
    "I wandered lonely as a cloud.",
    "To be or not to be, that is the question.",
    "Hope springs eternal in the human breast.",
    "The best is yet to be.",
    "I have measured out my life with coffee spoons."
];
// build functions to randomise the array data

// export the functions.

